name: Build and Push Images to GitHub Container Registry (GHCR)
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  - push
  - workflow_dispatch
jobs:
  Build-And-Push:
    name: Build and Push Application Images
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Check out repository code
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # https://github.com/docker/login-action#github-container-registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # An alternative to the following steps is to use the build-push-action: https://github.com/docker/build-push-action
      - name: Build and Push the Frontend Docker Image
        run: |
          docker build ./frontend --tag ghcr.io/${{ github.actor }}/bootcamp-gds-frontend:${{ github.sha }}
          docker push ghcr.io/${{ github.actor }}/bootcamp-gds-frontend:${{ github.sha }}
      - name: Build and Push the Backend Docker Image
        run: |
          docker build ./backend --tag ghcr.io/${{ github.actor }}/bootcamp-gds-backend:${{ github.sha }}
          docker push ghcr.io/${{ github.actor }}/bootcamp-gds-backend:${{ github.sha }}
      - name: Copy the images with their tags to your docker-compose.yml
        run: |
          echo "ghcr.io/${{ github.actor }}/bootcamp-gds-frontend:${{ github.sha }}"
          echo "ghcr.io/${{ github.actor }}/bootcamp-gds-backend:${{ github.sha }}"